### ISSUE TITLE
Doesn't Work For Non-Host

### ISSUE THREAD

**Issue by Tactical-Shrubbery** [JereKuusela/valheim-infinity_hammer#1]
We both had the mod installed and configured the same, but while it worked for my friend, it did not work for me. It still worked in singleplayer, however.

**Comment by JereKuusela** [comment]
You need cheats enabled to use it on servers. This is done to make griefing bit more harder.

For cheats you can try Dedicated Server Devcommands which enables cheats for admins or any other similar mod.
