### ISSUE TITLE
Auto Repair

### ISSUE THREAD

**Issue by SwarmoGyats0** [JereKuusela/valheim-infinity_hammer#14]
[LogOutput.log](https://github.com/JereKuusela/valheim-infinity_hammer/files/8639916/LogOutput.log)
There seems to be a malfunction in the interaction between Infinity Hammer and Automatics and/or Ward Is Love, as referenced in the log.

**Comment by JereKuusela** [comment]
Could you test if version 1.13 fixed this?

**Comment by SwarmoGyats0** [comment]
No sign of the error now!
