### ISSUE TITLE
This is not an Issue, it is a request (sorry but I did not know where I could give u a comment)

### ISSUE THREAD

**Issue by rexccon** [JereKuusela/valheim-infinity_hammer#16]
I was wondering if it **would be possible to add** the portal stone and the guard stone test **in the empty slots of the hammer** or some way to add the item we want to have quick access to it without copying the commands, **I'll stay tuned to your comments.** Thanks
> ![imagen_2022-05-10_180617102](https://user-images.githubusercontent.com/86977685/167738916-3aa541b8-a1bd-4230-b9f7-ea096a2d165a.png)
> ![imagen_2022-05-10_180655344](https://user-images.githubusercontent.com/86977685/167738965-fba0ade1-ba5e-49fd-9c74-aca0fe172da4.png)

**Comment by JereKuusela** [comment]
The idea is nice but out of scope for this mod. Maybe if I have enough spare some day I can think of creating a new mod for that. ;D
