### ISSUE TITLE
[Bug] Adjusting offset isn't holding that certain snap point anymore

### ISSUE THREAD

**Issue by virtualbjorn** [JereKuusela/valheim-infinity_hammer#17]
I've been able to adjust offsets just fine before and now it doesn't seem to hold on to the snap points. No errors in logs shown. I have to manually hover the mouse to a certain extent to make it snap back in as I adjust the offset repeatedly

**Comment by JereKuusela** [comment]
[InfinityHammer.zip](https://github.com/JereKuusela/valheim-infinity_hammer/files/8685112/InfinityHammer.zip)

Can you try this?

**Comment by virtualbjorn** [comment]
Trying it now, I just got off work so I have time now.

**Comment by virtualbjorn** [comment]
Just tried it. Seems to have fixed the snapping problem

**Comment by virtualbjorn** [comment]
One thing I found out that was change is that I could no longer offset a piece to a an area while there's a mob/entity in that certain position

**Comment by JereKuusela** [comment]
That was an intended change. So that you can't use offset to bypass build restrictions.

Turning on "Ignore other restrictions" allows you to build over mobs.
