### ISSUE TITLE
[Bug] Seems rectangly has it's width and length swapped for world edit commands?

### ISSUE THREAD

**Issue by KairuByte** [JereKuusela/valheim-infinity_hammer#32]
Not sure how to go into a lot of detail here... When I use InfinityHammer with WorldEdit and utilize the hoe, it seems that rectangle measurements are ignored, instead treating it like a square using the width as an absolute. 

A picture example:
![image](https://user-images.githubusercontent.com/393806/210901450-8c7f8199-7e1d-4c44-9ff2-52fe6e8c0f3e.png)
![image](https://user-images.githubusercontent.com/393806/210901455-cc467b40-d437-4122-8f70-cbd11c49526c.png)

**Comment by JereKuusela** [comment]
Thanks, fix is coming today.

**Comment by KairuByte** [comment]
2991e84e4647ab8150c40b612ef956b04375c32d seems to have corrected the issue, closing.
