### ISSUE TITLE
[Bug] Setting slope width

### ISSUE THREAD

**Issue by KairuByte** [JereKuusela/valheim-infinity_hammer#33]
When creating a slope with InfinityHammer+WorldEdit, slope width is wonky. You are able to change the length of the displayed rectangle, however the actual value which seems to be effected is depth? Except depth doesn't seem to change the result. And when depth is larger than the width, the width increases.

It feels like the changed value should be width, not depth.

![image](https://user-images.githubusercontent.com/393806/210904274-777c50fd-f035-4f68-9e6b-711e29b62157.png)

**Comment by JereKuusela** [comment]
Thanks, fix is coming today.

**Comment by KairuByte** [comment]
2991e84e4647ab8150c40b612ef956b04375c32d seems to have corrected the issue, closing.
