### ISSUE TITLE
[Bug] Repairing players causes a disconnect

### ISSUE THREAD

**Issue by KairuByte** [JereKuusela/valheim-infinity_hammer#35]
When you attempt to repair a player, that player disconnects. Any player singularly disconnected when this happens (meaning all other players remain connected and the server does not crash/roll back) will reconnect at their spawn point.

In rare cases, the entire server appears to crash, and all players are immediately disconnected. It happens in such a way that ServerCharacters by smoothbrain does not seem to be able to activate it's emergency save. Any disconnected players are reverted to their most recent save, as is the server map.

**Comment by JereKuusela** [comment]
Repairing players should be now blocked.
