### ISSUE TITLE
Pipette or 'hammer command' not working with trees if used together with BetterCreative

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-infinity_hammer#37]
If I use the Pipette to pick up a tree or use the hammer command (e.g. ´hammer oak1´) it works fine.

If I also install BetterCreative [1][2], this does not work anymore. It still works on rocks, etc

I will also add a bug report for BetterCreative

[1] https://valheim.thunderstore.io/package/Heinermann/BetterCreative/
[2] https://github.com/heinermann/Valheim_mods/tree/main/BetterCreative

**Comment by JereKuusela** [comment]
Unfortunately Better Creative does some stuff that makes things not working very well. It's not something I could fix easily.
