### ISSUE TITLE
[feature idea] Add all game prefabs to the build hammer

### ISSUE THREAD

**Issue by himpich** [JereKuusela/valheim-infinity_hammer#38]
The Mod BetterCreative [1] adds several tabs to the normal build hammer - with all prefabs of the game. I would love to see that as a feature in Infinity Hammer

[1] https://github.com/heinermann/Valheim_mods/tree/main/BetterCreative

**Comment by JereKuusela** [comment]
Maybe some day when I got enough spare time. 😁

**Comment by JereKuusela** [comment]
https://thunderstore.io/c/valheim/p/Searica/More_Vanilla_Build_Prefabs/ handles this.
