### ISSUE TITLE
Missing bit of Terrein after using Raise

### ISSUE THREAD

**Issue by StepGamerTv** [JereKuusela/valheim-infinity_hammer#40]
After i used raise my terrain act funny like there was nothing there but textures are still there, mobs and player walk in to it and go staring down to water level underground and bounce untill it move to terrain which was untouch with raise.
Piss help as this make my world unplayeble as i use this in my base...

**Comment by JereKuusela** [comment]
Terrain reset should fix this. There is also now minimum radius to prevent this from happening.
