### ISSUE TITLE
the new update from infinity_hammer broke anothers mod feature and i dont know how to fix it

### ISSUE THREAD

**Issue by Scarylaw** [JereKuusela/valheim-infinity_hammer#47]
im using the mod planteasily where you can plant multiple plants in a grid.
until today everything always worked fine but now i got an update on infinity_hammer and now its broken.
no matter how big the grid is it always plants them in 1 spot so i have like 20 plants in 1 spot. if i disable infinity hammer it works again.
even if i go in the cfg file and disable pretty much every feature it still is broken. it only works if i completly disable the hammer mod which is very annoying for me because i sertantly wont play without the planteasily mod.

**Comment by Blackmadman** [comment]
Hi, I have exactly the same problem. I hope you find a solution quickly and release a hotfix. It would be a shame to no longer be able to use my beloved hammer.

**Comment by JereKuusela** [comment]
This has been fixed in the version 1.45
