### ISSUE TITLE
Hammer_add command no longer works

### ISSUE THREAD

**Issue by Natalwho** [JereKuusela/valheim-infinity_hammer#51]
Using the hammer_add command no longer works (I have both infinity hammer and infinity tools) and all my previously added prefabs are no longer there.

**Comment by JereKuusela** [comment]
There is now a new file for them infinity_tools.yaml. You might be able to copy over your old ones from infinity_hammer.yaml but the format has changed quite a bit so might need tweaking.

Unfortunately hammer_add is no longer supported since there are lot more options now.
