### ISSUE TITLE
Repeating Error Message after Update

### ISSUE THREAD

**Issue by Ser-Loras** [JereKuusela/valheim-infinity_hammer#53]
Since the update I have been having issues with repeated error messages. It seems to start after I activate fly mode. I also noticed it happen once when I used the "goto" command to teleport a long distance.

`[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.List1<ZNetView> .ZoneLocation.m_netViews Due to: Could not find field in class
Stack trace:
(wrapper dynamic-method) ZoneSystem.DMD<ZoneSystem::SpawnLocation>(ZoneSystem,ZoneSystem/ZoneLocation,int,UnityEngine.Vector3,UnityEngine.Quaternion,ZoneSystem/SpawnMode,System.Collections.Generic.List1<UnityEngine.GameObject>)
ZoneSystem.PlaceLocations (Vector2i zoneID, UnityEngine.Vector3 zoneCenterPos, UnityEngine.Transform parent, Heightmap hmap, System.Collections.Generic.List1[T] clearAreas, ZoneSystem+SpawnMode mode, System.Collections.Generic.List1[T] spawnedObjects) (at <da52c09f594f4a7480000b7420815ba7>:0)
ZoneSystem.SpawnZone (Vector2i zoneID, ZoneSystem+SpawnMode mode, UnityEngine.GameObject& root) (at <da52c09f594f4a7480000b7420815ba7>:0)
ZoneSystem.CreateGhostZones (UnityEngine.Vector3 refPoint) (at <da52c09f594f4a7480000b7420815ba7>:0)
ZoneSystem.Update () (at <da52c09f594f4a7480000b7420815ba7>:0)
`

When the error occurs, the game continues to run for the most part, but I see an endless string of the same repeated error message spamming the console, and the game suddenly begins to be very resource intensive for my computer. Sometimes the game will eventually freeze, but not always.

I have removed all my mods and the issue does not occur. I then added back Server Devcommands and WorldEdit Commands and tried flying around, with no issues. Then I added Infinity Hammer back and tried flying around and the issue started again. I have downloaded all the lastest versions of Server DevCommands, World Edit, and Infinity Version currently available.

I've attached a log showing the error message below.
[LogOutput.log](https://github.com/JereKuusela/valheim-infinity_hammer/files/14938390/LogOutput.log)

**Comment by Ser-Loras** [comment]
I've now encountered this endless series of repeated error messages as soon as I load into the world with the Infinity Hammer mod installed.

Sometimes the error does not show up, or goes away after a few minutes though. However, I also no longer see the pipette, building selection, and area selection tools in my build menu. When I use the "hammer" command or "hammer_blueprint" to select a build piece I am unable to select a different build piece from the build menu.

**Comment by JereKuusela** [comment]
This should be now fixed.
