### ISSUE TITLE
Not compatable with BetterCreative

### ISSUE THREAD

**Issue by Wmonnh6** [JereKuusela/valheim-infinity_hammer#56]
Currently there is a bug where when this mod is used with the better creative mod it prevents you from breaking build pieces. and gives this error.
[Error  : Unity Log] MissingMethodException: Method not found: void .Piece.DropResources()
Stack trace:
(wrapper dynamic-method) Player.DMD<Player::RemovePiece>(Player)
(wrapper dynamic-method) Player.DMD<Player::UpdatePlacement>(Player,bool,single)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by JereKuusela** [comment]
Better Creative itself is probaby ultra broken.
