### ISSUE TITLE
not compatible with BepInEx

### ISSUE THREAD

**Issue by golden-vale** [JereKuusela/valheim-infinity_hammer#57]
hello, im new to mod, and i have a trouble when i try to load Bepinex mod with Infinity hammer.
it says
"[Error  :   BepInEx] Could not load [Infinity Hammer 1.56] because it has missing dependencies: server_devcommands (v1.76 or newer)"

is there something wrong with the Bepinex mod or the infinity hammer mod?
i tried multiple version of the infinity hammer mod, 1.56.0, 1.54.0, 1.50.0, 1.43.0, 1.41.0, 1.39.0
and all doesnt work, the first 3 version i mentioned, was just saying the same error message. last 3 version i mentioned was even worse, it just lagged and crashed the whole game.
how do i fix this issue?

**Comment by xVilho** [comment]
You need to have server_devcommands installed as ur error states here: missing dependencies: server_devcommands.
https://thunderstore.io/c/valheim/p/JereKuusela/Server_devcommands/changelog/
Ps. I have nothing to do with coding this mod. Just user passing by.

**Comment by golden-vale** [comment]
i just saw your reply, and just tried it out, and it works! all the mods are working and no error messages anymore, thankyou so much for your reply!
