### ISSUE TITLE
Invulnerability options causing problems

### ISSUE THREAD

**Issue by om2j** [JereKuusela/valheim-infinity_hammer#59]
Hi! Thank you for this mod.

When you repair things with the invulnerability option ON (not damaged, worn, or legacy), the item becomes indeed invulnerable, but the health is set at 0 and the texture is also of the most worn-out state. None of the other options allow me to keep the best state's texture while invulnerable. The overwrite health option doesn't seem to work either and brings health to 0.

Would there also be a way to remove the invulnerability and reset to the original health?

**Comment by JereKuusela** [comment]
This should now work more logically on the latest version.
